# Generated by Django 3.1.7 on 2021-04-28 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bisiklet', '0002_yorum'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='brand',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Marka Adı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urun',
            name='gear',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Vites'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urun',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Cinsiyet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urun',
            name='medicine',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Bisiklet Tipi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urun',
            name='price',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Fiyat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urun',
            name='rim',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Jant'),
            preserve_default=False,
        ),
    ]
