# Generated by Django 3.1.7 on 2021-05-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisiklet', '0004_deneme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='medicine',
            field=models.CharField(choices=[('dag', 'Dağ Bisikleti'), ('yol', 'Yol-Yarış Bisikleti'), ('sehir', 'Şehir Bisikleti'), ('cocuk', 'Çocuk Bisikleti')], default='Bisiklet Tipi Seçiniz', max_length=50, verbose_name='Bisiklet Tipi'),
        ),
    ]
