# Generated by Django 3.1.7 on 2021-05-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisiklet', '0005_auto_20210502_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='gender',
            field=models.CharField(choices=[('erkek', 'Erkek'), ('kadın', 'Kadın'), ('erkekcocuk', 'Erkek Çocuk'), ('kızcocuk', 'Kız Çocuk')], max_length=50, verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='medicine',
            field=models.CharField(choices=[('dag', 'Dağ Bisikleti'), ('yol', 'Yol-Yarış Bisikleti'), ('sehir', 'Şehir Bisikleti'), ('cocuk', 'Çocuk Bisikleti')], max_length=50, verbose_name='Bisiklet Tipi'),
        ),
    ]
