# Generated by Django 3.1.7 on 2021-05-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisiklet', '0008_auto_20210505_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='gender',
            field=models.CharField(choices=[('seciniz', 'Seçiniz'), ('Erkek', 'Erkek'), ('Kadın', 'Kadın'), ('Erkek Çocuk', 'Erkek Çocuk'), ('Kız Çocuk', 'Kız Çocuk'), ('Unisex', 'Unisex')], default='seciniz', max_length=50, verbose_name='Cinsiyet'),
        ),
    ]
